separator_block_width=10

# Volume {{{
command=/usr/libexec/i3blocks/volume
LABEL=♪ 
interval=once
signal=10

# }}}

[swap]
command=/usr/libexec/i3blocks/memory swap
interval=30

# disk {{{
# [disk-home]
# command=/usr/local/libexec/i3blocks/disk $HOME
# interval=30
# }}}

# Network IP {{{
# [External IP]
# command=curl ifconfig.me
# color=#00FF00
# interval=6000
# separator=false
# 
# [wireless]
# command=/usr/local/libexec/i3blocks/network wlp5s7 W
# color=#00FF00
# interval=10

# [ethernet]
# command=/usr/local/libexec/i3blocks/network eth0 E
# color=#00FF00
# interval=10
# }}}

# System Info {{{
# [cpu]
# command=/usr/libexec/i3blocks/cpu_usage
# interval=10

[iface]
command=/usr/libexec/i3blocks/iface
interval=60

[battery]
command=/usr/libexec/i3blocks/battery
interval=60

[sway-focusedwindow]
command=/usr/libexec/i3blocks/sway-focusedwindow
interval=10

[mem]
command=/usr/libexec/i3blocks/memory
interval=30

# [temp]
# command=/usr/libexec/i3blocks/temperature
# interval=10

[temp]
command=echo "$(sensors coretemp-isa-0000  | awk '/Core 0:/ {print $3}') $(sensors coretemp-isa-0000  | awk '/Core 1:/ {print $3}') "
interval=5
color=#b58900

# Bolsa {{{
# [ibex35]
# command=perl6 ~/.config/Repos/bin/IndexBolsa.raku ibex35
# interval=60
# 
# [eurostoxx50]
# command=perl6 ~/.config/Repos/bin/IndexBolsa.raku eurostoxx
# interval=60
# 
# [sp500]
# command=perl6 ~/.config/Repos/bin/IndexBolsa.raku sp500
# interval=60
# 
# [ING_Renta_Fija]
# command=perl6 ~/.config/Repos/bin/IndexBolsa.raku ing_renta_fija
# interval=14400
# }}}

# time {{{
[time]
command=date '+%d/%m %H:%M:%S'
interval=1
# [timeVE]
# command=TZ="America/Caracas" date '+%H:%M VE'
# interval=5
# }}}
